version: '3.1'

services:
  db:
    image: mariadb:11.1.3
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${KLEO_DB_ROOT_PASSWORD}
      MARIADB_USER: ${KLEO_DB_USER}
      MARIADB_PASSWORD: ${KLEO_DB_PASSWORD}
      MARIADB_DATABASE: ${KLEO_DB_NAME}
    volumes:
      - kleodb:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  kleodb:
